### ISSUE TITLE
Don't show message every time, just add the line!

### ISSUE THREAD

**Issue by richarddavenport** [riccardoNovaglia/vsCodeBlankLine#1]
I love this extension, but I think if you added a configuration for not showing the message it would be helpful. If most people are like me, I added the extension because I wanted the line at the end of the file. I think a good start to configuration would be to show the message or not. If you would like a PR let me know, I'm sure I could get this done.

**Comment by riccardoNovaglia** [comment]
Thanks for the kind words, as for the configs I'm on it! I'll see if I can sneak some time on this today, otherwise I'll take care of it during the weekend. Thanks for the feedback!

**Comment by riccardoNovaglia** [comment]
Done! Give it a go and let me know if you spot any other problems!

Thanks again for the feedback
