### ISSUE TITLE
doesn't append line to 1-line files

### ISSUE THREAD

**Issue by famousgarkin** [riccardoNovaglia/vsCodeBlankLine#3]
Any reason for this?

**Comment by riccardoNovaglia** [comment]
Hi Jan! I think I put in some logic to avoid appending to blank files, not
sure if 1 line was included. I'm away on holidays at the moment but I will
look into in when I get back

**Comment by riccardoNovaglia** [comment]
Hey, just FYI, I'm on it. I'm fixing things around, I'll push the new version by tomorrow night I think

**Comment by riccardoNovaglia** [comment]
Fixed, sorry it took a while. I've just published the new version so you can go ahead and update.
Thanks again for reporting it!
