### ISSUE TITLE
blankLine.showMessage doesn't work anymore

### ISSUE THREAD

**Issue by Loghorn** [riccardoNovaglia/vsCodeBlankLine#4]
The options to disable the revert message used to work. In the latest update it doesn't and the message is always shown. Also, selecting "close" does a revert instead of keeping the white line.

**Comment by riccardoNovaglia** [comment]
I'll get right on it as soon as I'm back from work, thanks for letting me
know!

**Comment by riccardoNovaglia** [comment]
Hi Alessandro, should be all fixed now, I've published the new version. Thanks again for letting me know!

**Comment by Loghorn** [comment]
Riccardo, thank you for fixing it so quickly 😄
