### ISSUE TITLE
Remove Extraneous Blank Lines

### ISSUE THREAD

**Issue by jacobp100** [riccardoNovaglia/vsCodeBlankLine#6]
If my file has say 3 blank lines at the end, would it be possible to remove the extra ones, so there's exactly one blank line at the end of the file? I believe this is the behaviour of atom.

**Comment by riccardoNovaglia** [comment]
Hey, missed the notification from github, not sure if this is still relevant. I think that's a useful feature to add, I'll have a look over the weekend.
